[workspace]

resolver = "2"

members = [
    "ibc-chain-registry",
    "modules",
    "relayer",
    "relayer-cli",
    "relayer-rest",
    "telemetry",
    "proto",
    "tools/integration-test",
    "tools/test-framework",
]

exclude = [
    "ci/no-std-check",
    "proto-compiler",
    "relayer-x/ibc-proxy",
]

[patch.crates-io]
tendermint                       = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
tendermint-rpc                   = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
tendermint-proto                 = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
tendermint-light-client          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
tendermint-light-client-verifier = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
tendermint-testgen               = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
