[package]
name = "ext-light-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc = { path = "../../modules", default-features = false }
ibc-proto = { path = "../../proto", default-features = false }
serde = { version = "1.0", default-features = false }
